[2022-02-01 15:19:16,960] {processor.py:163} INFO - Started process (PID=35) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:19:16,962] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:19:16,964] {logging_mixin.py:109} INFO - [2022-02-01 15:19:16,964] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:19:16,970] {logging_mixin.py:109} INFO - [2022-02-01 15:19:16,969] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:19:17,003] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:19:17,031] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.076 seconds
[2022-02-01 15:19:47,643] {processor.py:163} INFO - Started process (PID=90) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:19:47,646] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:19:47,647] {logging_mixin.py:109} INFO - [2022-02-01 15:19:47,647] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:19:47,649] {logging_mixin.py:109} INFO - [2022-02-01 15:19:47,648] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:19:47,672] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:19:47,686] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2022-02-01 15:20:18,133] {processor.py:163} INFO - Started process (PID=143) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:20:18,135] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:20:18,136] {logging_mixin.py:109} INFO - [2022-02-01 15:20:18,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:20:18,138] {logging_mixin.py:109} INFO - [2022-02-01 15:20:18,137] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:20:18,156] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:20:18,163] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2022-02-01 15:20:48,436] {processor.py:163} INFO - Started process (PID=203) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:20:48,437] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:20:48,438] {logging_mixin.py:109} INFO - [2022-02-01 15:20:48,438] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:20:48,440] {logging_mixin.py:109} INFO - [2022-02-01 15:20:48,439] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:20:48,463] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:20:48,472] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2022-02-01 15:21:19,122] {processor.py:163} INFO - Started process (PID=254) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:21:19,123] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:21:19,124] {logging_mixin.py:109} INFO - [2022-02-01 15:21:19,124] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:21:19,127] {logging_mixin.py:109} INFO - [2022-02-01 15:21:19,126] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:21:19,142] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:21:19,160] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.041 seconds
[2022-02-01 15:21:49,525] {processor.py:163} INFO - Started process (PID=317) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:21:49,526] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:21:49,527] {logging_mixin.py:109} INFO - [2022-02-01 15:21:49,527] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:21:49,529] {logging_mixin.py:109} INFO - [2022-02-01 15:21:49,528] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:21:49,549] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:21:49,559] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2022-02-01 15:22:19,829] {processor.py:163} INFO - Started process (PID=369) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:22:19,830] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:22:19,830] {logging_mixin.py:109} INFO - [2022-02-01 15:22:19,830] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:22:19,832] {logging_mixin.py:109} INFO - [2022-02-01 15:22:19,832] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:22:19,846] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:22:19,854] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.028 seconds
[2022-02-01 15:22:50,261] {processor.py:163} INFO - Started process (PID=420) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:22:50,263] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:22:50,263] {logging_mixin.py:109} INFO - [2022-02-01 15:22:50,263] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:22:50,267] {logging_mixin.py:109} INFO - [2022-02-01 15:22:50,266] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:22:50,283] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:22:50,296] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-02-01 15:23:21,087] {processor.py:163} INFO - Started process (PID=482) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:23:21,089] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:23:21,089] {logging_mixin.py:109} INFO - [2022-02-01 15:23:21,089] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:23:21,093] {logging_mixin.py:109} INFO - [2022-02-01 15:23:21,092] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:23:21,109] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:23:21,121] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.037 seconds
[2022-02-01 15:23:51,701] {processor.py:163} INFO - Started process (PID=535) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:23:51,703] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:23:51,704] {logging_mixin.py:109} INFO - [2022-02-01 15:23:51,704] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:23:51,708] {logging_mixin.py:109} INFO - [2022-02-01 15:23:51,707] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:23:51,726] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:23:51,736] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
[2022-02-01 15:24:22,444] {processor.py:163} INFO - Started process (PID=597) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:24:22,445] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:24:22,447] {logging_mixin.py:109} INFO - [2022-02-01 15:24:22,446] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:24:22,450] {logging_mixin.py:109} INFO - [2022-02-01 15:24:22,449] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:24:22,467] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:24:22,476] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-02-01 15:24:52,713] {processor.py:163} INFO - Started process (PID=648) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:24:52,715] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:24:52,716] {logging_mixin.py:109} INFO - [2022-02-01 15:24:52,716] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:24:52,719] {logging_mixin.py:109} INFO - [2022-02-01 15:24:52,718] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:24:52,735] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:24:52,743] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2022-02-01 15:25:23,047] {processor.py:163} INFO - Started process (PID=718) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:25:23,048] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:25:23,049] {logging_mixin.py:109} INFO - [2022-02-01 15:25:23,049] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:25:23,053] {logging_mixin.py:109} INFO - [2022-02-01 15:25:23,052] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:25:23,069] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:25:23,079] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-02-01 15:25:53,243] {processor.py:163} INFO - Started process (PID=774) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:25:53,245] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:25:53,245] {logging_mixin.py:109} INFO - [2022-02-01 15:25:53,245] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:25:53,248] {logging_mixin.py:109} INFO - [2022-02-01 15:25:53,247] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:25:53,264] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:25:53,271] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.032 seconds
[2022-02-01 15:26:23,409] {processor.py:163} INFO - Started process (PID=835) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:26:23,410] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:26:23,411] {logging_mixin.py:109} INFO - [2022-02-01 15:26:23,411] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:26:23,413] {logging_mixin.py:109} INFO - [2022-02-01 15:26:23,412] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:26:23,428] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:26:23,438] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.034 seconds
[2022-02-01 15:26:53,749] {processor.py:163} INFO - Started process (PID=886) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:26:53,761] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:26:53,762] {logging_mixin.py:109} INFO - [2022-02-01 15:26:53,762] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:26:53,765] {logging_mixin.py:109} INFO - [2022-02-01 15:26:53,764] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:26:53,785] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:26:53,792] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2022-02-01 15:27:24,110] {processor.py:163} INFO - Started process (PID=947) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:27:24,111] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:27:24,112] {logging_mixin.py:109} INFO - [2022-02-01 15:27:24,112] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:27:24,116] {logging_mixin.py:109} INFO - [2022-02-01 15:27:24,115] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:27:24,136] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:27:24,156] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2022-02-01 15:27:54,932] {processor.py:163} INFO - Started process (PID=1001) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:27:54,936] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:27:54,937] {logging_mixin.py:109} INFO - [2022-02-01 15:27:54,937] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:27:54,941] {logging_mixin.py:109} INFO - [2022-02-01 15:27:54,940] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:27:54,970] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:27:54,984] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2022-02-01 15:28:25,904] {processor.py:163} INFO - Started process (PID=1070) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:28:25,906] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:28:25,907] {logging_mixin.py:109} INFO - [2022-02-01 15:28:25,907] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:28:25,914] {logging_mixin.py:109} INFO - [2022-02-01 15:28:25,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:28:25,933] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:28:25,945] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.045 seconds
[2022-02-01 15:28:56,367] {processor.py:163} INFO - Started process (PID=1123) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:28:56,368] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:28:56,369] {logging_mixin.py:109} INFO - [2022-02-01 15:28:56,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:28:56,372] {logging_mixin.py:109} INFO - [2022-02-01 15:28:56,371] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:28:56,388] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:28:56,398] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-02-01 15:29:26,823] {processor.py:163} INFO - Started process (PID=1175) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:29:26,825] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:29:26,826] {logging_mixin.py:109} INFO - [2022-02-01 15:29:26,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:29:26,828] {logging_mixin.py:109} INFO - [2022-02-01 15:29:26,828] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:29:26,845] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:29:26,852] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.033 seconds
[2022-02-01 15:29:57,843] {processor.py:163} INFO - Started process (PID=1237) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:29:57,845] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:29:57,846] {logging_mixin.py:109} INFO - [2022-02-01 15:29:57,846] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:29:57,850] {logging_mixin.py:109} INFO - [2022-02-01 15:29:57,848] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:29:57,865] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:29:57,875] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-02-01 15:30:28,090] {processor.py:163} INFO - Started process (PID=1294) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:30:28,092] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:30:28,092] {logging_mixin.py:109} INFO - [2022-02-01 15:30:28,092] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:30:28,096] {logging_mixin.py:109} INFO - [2022-02-01 15:30:28,095] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:30:28,111] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:30:28,122] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-02-01 15:30:58,446] {processor.py:163} INFO - Started process (PID=1350) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:30:58,447] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:30:58,448] {logging_mixin.py:109} INFO - [2022-02-01 15:30:58,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:30:58,451] {logging_mixin.py:109} INFO - [2022-02-01 15:30:58,450] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:30:58,468] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:30:58,477] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.035 seconds
[2022-02-01 15:31:29,153] {processor.py:163} INFO - Started process (PID=1401) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:31:29,155] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:31:29,155] {logging_mixin.py:109} INFO - [2022-02-01 15:31:29,155] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:31:29,158] {logging_mixin.py:109} INFO - [2022-02-01 15:31:29,157] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:31:29,173] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:31:29,185] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.036 seconds
[2022-02-01 15:31:59,600] {processor.py:163} INFO - Started process (PID=1464) to work on /opt/airflow/dags/first_dag.py
[2022-02-01 15:31:59,601] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2022-02-01 15:31:59,601] {logging_mixin.py:109} INFO - [2022-02-01 15:31:59,601] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2022-02-01 15:31:59,604] {logging_mixin.py:109} INFO - [2022-02-01 15:31:59,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:31:59,622] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2022-02-01 15:31:59,635] {processor.py:171} INFO - Processing /opt/airflow/dags/first_dag.py took 0.039 seconds
