[2022-02-01 15:10:06,852] {processor.py:163} INFO - Started process (PID=40) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:10:06,853] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:10:06,854] {logging_mixin.py:109} INFO - [2022-02-01 15:10:06,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:10:06,857] {logging_mixin.py:109} INFO - [2022-02-01 15:10:06,856] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:10:06,887] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:10:06,918] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.070 seconds
[2022-02-01 15:10:37,093] {processor.py:163} INFO - Started process (PID=91) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:10:37,094] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:10:37,095] {logging_mixin.py:109} INFO - [2022-02-01 15:10:37,095] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:10:37,100] {logging_mixin.py:109} INFO - [2022-02-01 15:10:37,097] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:10:37,122] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:10:37,144] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.055 seconds
[2022-02-01 15:11:08,004] {processor.py:163} INFO - Started process (PID=152) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:11:08,005] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:11:08,006] {logging_mixin.py:109} INFO - [2022-02-01 15:11:08,006] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:11:08,010] {logging_mixin.py:109} INFO - [2022-02-01 15:11:08,009] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:11:08,032] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:11:08,045] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.046 seconds
[2022-02-01 15:11:38,462] {processor.py:163} INFO - Started process (PID=208) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:11:38,463] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:11:38,464] {logging_mixin.py:109} INFO - [2022-02-01 15:11:38,464] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:11:38,467] {logging_mixin.py:109} INFO - [2022-02-01 15:11:38,466] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:11:38,484] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:11:38,492] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.033 seconds
[2022-02-01 15:13:55,518] {processor.py:163} INFO - Started process (PID=37) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:13:55,520] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:13:55,523] {logging_mixin.py:109} INFO - [2022-02-01 15:13:55,523] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:13:55,527] {logging_mixin.py:109} INFO - [2022-02-01 15:13:55,525] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:13:55,562] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:13:55,587] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.072 seconds
[2022-02-01 15:14:26,276] {processor.py:163} INFO - Started process (PID=90) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:14:26,277] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:14:26,278] {logging_mixin.py:109} INFO - [2022-02-01 15:14:26,277] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:14:26,280] {logging_mixin.py:109} INFO - [2022-02-01 15:14:26,280] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:14:26,295] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:14:26,307] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.035 seconds
[2022-02-01 15:14:56,745] {processor.py:163} INFO - Started process (PID=144) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:14:56,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:14:56,748] {logging_mixin.py:109} INFO - [2022-02-01 15:14:56,747] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:14:56,750] {logging_mixin.py:109} INFO - [2022-02-01 15:14:56,749] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:14:56,769] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:14:56,781] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.039 seconds
[2022-02-01 15:15:27,295] {processor.py:163} INFO - Started process (PID=206) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:15:27,296] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:15:27,297] {logging_mixin.py:109} INFO - [2022-02-01 15:15:27,297] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:15:27,301] {logging_mixin.py:109} INFO - [2022-02-01 15:15:27,299] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:15:27,320] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:15:27,330] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.039 seconds
[2022-02-01 15:15:57,856] {processor.py:163} INFO - Started process (PID=258) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:15:57,857] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:15:57,858] {logging_mixin.py:109} INFO - [2022-02-01 15:15:57,858] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:15:57,861] {logging_mixin.py:109} INFO - [2022-02-01 15:15:57,860] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:15:57,879] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:15:57,888] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.037 seconds
[2022-02-01 15:16:28,401] {processor.py:163} INFO - Started process (PID=319) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:16:28,403] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:16:28,404] {logging_mixin.py:109} INFO - [2022-02-01 15:16:28,404] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:16:28,405] {logging_mixin.py:109} INFO - [2022-02-01 15:16:28,405] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:16:28,429] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:16:28,438] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.041 seconds
[2022-02-01 15:16:58,740] {processor.py:163} INFO - Started process (PID=372) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:16:58,741] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:16:58,741] {logging_mixin.py:109} INFO - [2022-02-01 15:16:58,741] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:16:58,743] {logging_mixin.py:109} INFO - [2022-02-01 15:16:58,743] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 3, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:16:58,763] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:16:58,776] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.042 seconds
[2022-02-01 15:17:11,368] {processor.py:163} INFO - Started process (PID=414) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:17:11,369] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:17:11,370] {logging_mixin.py:109} INFO - [2022-02-01 15:17:11,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:17:11,372] {logging_mixin.py:109} INFO - [2022-02-01 15:17:11,372] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:17:11,389] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:17:11,400] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.036 seconds
[2022-02-01 15:17:41,824] {processor.py:163} INFO - Started process (PID=476) to work on /opt/airflow/dags/first_task.py
[2022-02-01 15:17:41,825] {processor.py:642} INFO - Processing file /opt/airflow/dags/first_task.py for tasks to queue
[2022-02-01 15:17:41,826] {logging_mixin.py:109} INFO - [2022-02-01 15:17:41,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/first_task.py
[2022-02-01 15:17:41,829] {logging_mixin.py:109} INFO - [2022-02-01 15:17:41,828] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/first_task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/first_task.py", line 2, in <module>
    import sleep
ModuleNotFoundError: No module named 'sleep'
[2022-02-01 15:17:41,848] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/first_task.py
[2022-02-01 15:17:41,859] {processor.py:171} INFO - Processing /opt/airflow/dags/first_task.py took 0.038 seconds
