[2022-02-01 16:12:02,460] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: first_dag.delay_function_execute scheduled__2022-02-01T16:10:00+00:00 [queued]>
[2022-02-01 16:12:02,472] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: first_dag.delay_function_execute scheduled__2022-02-01T16:10:00+00:00 [queued]>
[2022-02-01 16:12:02,472] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 16:12:02,472] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-01 16:12:02,472] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 16:12:02,485] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): delay_function_execute> on 2022-02-01 16:10:00+00:00
[2022-02-01 16:12:02,492] {standard_task_runner.py:52} INFO - Started process 1101 to run task
[2022-02-01 16:12:02,496] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'delay_function_execute', 'scheduled__2022-02-01T16:10:00+00:00', '--job-id', '987', '--raw', '--subdir', 'DAGS_FOLDER/firstdag.py', '--cfg-path', '/tmp/tmp9xx61mii', '--error-file', '/tmp/tmpzwv0ti1g']
[2022-02-01 16:12:02,496] {standard_task_runner.py:77} INFO - Job 987: Subtask delay_function_execute
[2022-02-01 16:12:02,564] {logging_mixin.py:109} INFO - Running <TaskInstance: first_dag.delay_function_execute scheduled__2022-02-01T16:10:00+00:00 [running]> on host 846ca9424c84
[2022-02-01 16:12:02,633] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=delay_function_execute
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T16:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T16:10:00+00:00
[2022-02-01 16:12:02,634] {logging_mixin.py:109} INFO - starting delay for 5 sec
[2022-02-01 16:12:07,638] {logging_mixin.py:109} INFO - 5 sec ends
[2022-02-01 16:12:07,638] {python.py:175} INFO - Done. Returned value was: dealy function ends
[2022-02-01 16:12:07,667] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=delay_function_execute, execution_date=20220201T161000, start_date=20220201T161202, end_date=20220201T161207
[2022-02-01 16:12:07,698] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-01 16:12:07,742] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
