[2022-02-01 16:16:02,326] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: first_dag.delay_function_execute scheduled__2022-02-01T16:14:00+00:00 [queued]>
[2022-02-01 16:16:02,337] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: first_dag.delay_function_execute scheduled__2022-02-01T16:14:00+00:00 [queued]>
[2022-02-01 16:16:02,337] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 16:16:02,337] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-01 16:16:02,337] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 16:16:02,351] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): delay_function_execute> on 2022-02-01 16:14:00+00:00
[2022-02-01 16:16:02,357] {standard_task_runner.py:52} INFO - Started process 1298 to run task
[2022-02-01 16:16:02,361] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'delay_function_execute', 'scheduled__2022-02-01T16:14:00+00:00', '--job-id', '993', '--raw', '--subdir', 'DAGS_FOLDER/firstdag.py', '--cfg-path', '/tmp/tmpte1k18we', '--error-file', '/tmp/tmpdmt31vk2']
[2022-02-01 16:16:02,362] {standard_task_runner.py:77} INFO - Job 993: Subtask delay_function_execute
[2022-02-01 16:16:02,437] {logging_mixin.py:109} INFO - Running <TaskInstance: first_dag.delay_function_execute scheduled__2022-02-01T16:14:00+00:00 [running]> on host 846ca9424c84
[2022-02-01 16:16:02,502] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=delay_function_execute
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T16:14:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T16:14:00+00:00
[2022-02-01 16:16:02,503] {logging_mixin.py:109} INFO - starting delay for 5 sec
[2022-02-01 16:16:07,506] {logging_mixin.py:109} INFO - 5 sec ends
[2022-02-01 16:16:07,506] {python.py:175} INFO - Done. Returned value was: dealy function ends
[2022-02-01 16:16:07,538] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=delay_function_execute, execution_date=20220201T161400, start_date=20220201T161602, end_date=20220201T161607
[2022-02-01 16:16:07,567] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-01 16:16:07,613] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
